name: NitsSkyblockCore
version: '${project.version}'
main: me.sirimperivm.spigot.Main
api-version: 1.19
load: STARTUP
description: Core della Season 2 dello Skyblock di NerdInTheSoul
authors:
  - SirImperivm_
softdepend:
  - PlaceholderAPI
depend:
  - Vault
  - WorldGuard

loadbefore:
  - WorldGuard

commands:
  skycore:
    aliases:
      - skyc
  racesadmin:
    aliases:
      - ra
  race:
    aliases:
      - races