settings:
  database:
    # Se sopra si ha selezionato "MySQL" qui sotto è obbligatorio inserire le credenziali di accesso;
    host: "192.168.1.2" # Questo è l'host del server in cui è ospitato il database.
    port: 3306 # Questa è la porta di accesso.
    user: "u54_ho8qHhlsf8" # Questo è l'username dell'utente mysql che avrà accesso al database.
    password: "kj30w=AG=gkQSC2e.8^Xis=z" # Questa è la password con cui l'utente mysql entrerà nel database (Lasciare vuoto se mysql accetta senza).
    name: "s54_skycore" # Questo è il nome del database.
    tablePrefix: "sc_" # Questo è il prefisso con cui iniziano le tabelle nel database (Se non si conosce cosa serve meglio non usarlo).
    options: "?useSSL=true" # Qua vengono messe le opzioni di collegamento.
  modules:
    races:
      enable: true
      defaultRaceRaw: "Nessuna"
      defaultRaceName: "&cN/A"
      day:
        start: 1500.0
        end: 13500.0
      durations:
        init: 999970
        end: 999999
      blockChat: false
      world-blacklist:
        - ExtremeCave
    destroyUnbreakable:
      enable: true
      world-blacklist:
        - ExtremeCave
      block-list:
        1:
          material: END_PORTAL_FRAME
          pickup:
            enabled: true
            in-inventory: true
        2:
          material: END_PORTAL
          pickup:
            enabled: false
            in-inventory: false
    extraCave:
      enable: true
      world-whitelist:
        - ExtremeCave
      regenerativeOre: CRACKED_STONE_BRICKS
      bypassMethods: true
      timeCooldowns:
        normal: 30
        deepslate: 60
        blockPlaced: 20
      block-break-list:
        - "COAL_ORE;true"
        - "IRON_ORE;true"
        - "GOLD_ORE;true"
        - "COPPER_ORE;true"
        - "LAPIS_ORE;true"
        - "REDSTONE_ORE;true"
        - "DIAMOND_ORE;true"
        - "EMERALD_ORE;true"
        - "DEEPSLATE_COAL_ORE;true"
        - "DEEPSLATE_IRON_ORE;true"
        - "DEEPSLATE_GOLD_ORE;true"
        - "DEEPSLATE_COPPER_ORE;true"
        - "DEEPSLATE_LAPIS_ORE;true"
        - "DEEPSLATE_REDSTONE_ORE;true"
        - "DEEPSLATE_DIAMOND_ORE;true"
        - "DEEPSLATE_EMERALD_ORE;true"
        - "COBBLESTONE;false"
        - "COBBLED_DEEPSLATE;false"
        - "DIRT;false"
        - "OAK_LOG;false"
        - "OAK_PLANKS;false"
        - "CRAFTING_TABLE;false"
        - "FURNACE;false"
        - "LADDER;false"
        - "SCULK_VEIN;false"
        - "GLOW_LICHEN;false"
      block-place-list:
        - "CRAFTING_TABLE;false"
        - "FURNACE;false"
        - "COBBLESTONE;true"
        - "COBBLED_DEEPSLATE;true"
        - "OAK_LOG;false"
        - "OAK_PLANKS;true"
        - "LADDER;true"
        - "DIRT;true"
      deny-messages:
        block-place: "%fpNon puoi piazzare questo blocco qui."
  strings:
    valueFormatSize: 5
    valueFormatting:
      - '1000.0-k'
      - '1000000.0-m'
      - '1000000000.0-M'
      - '1000000000000.0-b'
      - '1000000000000000.0-B'
      - '1000000000000000000.0-t'
      - '1000000000000000000000.0-T'
messages:
  prefixes:
    success: "&8[&a!&8] &7"
    info: "&8[&e!&8] &7"
    fail: "&8[&c!&8] &7"
  success:
    plugin:
      reloaded: "%spPlugin ricaricato correttamente."
    admin:
      races:
        created:
          - "&8&m                              "
          - "<SOLID:26AD39>&lRazza Creata!"
          - ""
          - "<SOLID:CAD224>Informazioni:"
          - " &e🟆 &7Nome: &e${raceName}"
          - " &e🟆 &7Titlo: &e${raceTitle}"
          - " &e🟆 &7Id: &e${raceId}"
          - "&8&m                              "
          - "${copyRaceId}"
        deleted: "%spRimossa la razza &a${raceName}&7."
        targets:
          set: "%spHai impostato la razza &a${raceName}&7 all'utente &a${username}&7."
          reset: "%spHai resettato la razza all'utente &a${username}&7."
    users:
      races:
        choose: "%spHai scelto la razza &a${raceName}&7."
        reset: "%spHai resettato la tua razza."
  info:
    admin:
      races:
        info:
          hasRace:
            - "&8&m                              "
            - "&8[&e!&8] &7L'utente fa parte della razza &e${raceName}&7."
            - "&8&m                              "
          hasntRace:
            - "&8&m                              "
            - "&8[&c!&8] &7L'utente non ha una razza."
            - "&8&m                              "
      extraCave:
        bypass:
          string: "%ipModalità bypass ExtraCave &e${status}&7."
          formats:
            enabled: "Attivata"
            disabled: "Disattivata"
          placeholderFormats:
            enabled: "&aBypass Attivo."
            disabled: "&cBypass non Attivo."
    users:
      races:
        received:
          from-admin: "%ipHai ricevuto la razza &e${raceName}&7 da un amministratore."
        reset:
          from-death: "%ipLa razza &e${raceName}&7 è stata eliminata, non ne fai più parte."
          from-admin: "%ipUn amministratore ha rimosso la tua razza."
    money:
     take: "&7- &e€${value-formatted}"
     give: "&7+ &e€${value-formatted}"
  errors:
    no-perm:
      command: "%fpNecessiti del permesso &c${node}&7 per eseguire questo comando."
      action: "%fpNecessiti del permesso &c${node}&7 per eseguire quest'azione."
    no-console: "%fpLa console non può eseguire questi comandi."
    admin:
      races:
        already-exists: "%fpEsiste già una razza con questo nome."
        dont-exists: "%fpNon esiste una razza con questo nome."
        targets:
          user-not-found: "%fpQuest'utente non è mai entrato nel server."
          already-have: "%fpL'utente ha già la razza richiesta."
          already-have-ones: "%fpL'utente ha già una razza."
          dont-have: "%fpL'utente non ha nessuna razza attiva al momento."
    users:
      races:
        dont-have: "%fpNon hai nessuna razza attiva al momento."
        dont-exists: "%fpLa razza scelta non esiste."
        already-have: "%fpHai già una razza."
    general:
      module-disabled: "%fpModulo non attivo."
      races:
        chat:
          not-allowed: "%fpPer poter chattare in chat devi scegliere una classe."
  others:
    admin:
      races:
        list:
          header: "&8&m                              "
          title: "<SOLID:26AD39>&lLista delle Razze:"
          spacer: ""
          lines:
            title: "<SOLID:CAD224>Razza:"
            line: " &e🟆 &f${raceName}"
          footer: "&8&m                              "
    users:
      races:
        list:
          header: "&8&m                              "
          title: "<SOLID:26AD39>&lLista delle Razze:"
          spacer: ""
          lines:
            title: "<SOLID:CAD224>Razza:"
            line: " &e🟆 &f${raceName}"
          footer: "&8&m                              "
permissions:
  admin-commands:
    core:
      main: skycore.admin.core.main
      reload: skycore.admin.core.reload
    races:
      main: skycore.admin.races.main
      create: skycore.admin.races.create
      delete: skycore.admin.races.delete
      targets:
        set: skycore.admin.races.target-set
        reset: skycore.admin.races.target-reset
        info: skycore.admin.races.info
      list: skycore.admin.races.list
    extraCave:
      main: skycore.admin.extracave.main
      bypass: skycore.admin.extracave.bypass
  user-commands:
    races:
      main: skycore.user.races.main
      gui: skycore.user.races.gui
      choose: skycore.user.races.choose_race
      getRace: skycore.getRace.<raceName>
      reset: skycore.user.races.reset_race
placeholders:
  user:
    race:
      name: user_race_name # Il placeholder relativo è %skycore_user_race_name% e mostrerà il nome della razza del player.
      title: user_race_title # Il placeholder relativo è %skycore_user_race_title% e mostrerà il titolo della razza del player.
    extraCave:
      bypassing: user_extraCave_bypassing # Il placeholder relativo è %skycore_user_extraCave_bypassing% e mosterà se il player sta bypassando o no il blocco della extraCave.